name: CI Pipeline

# Déclenche le workflow à chaque push ou pull request
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Utilise la dernière version 3.x de Python

      # Étape 3 : Installer les dépendances (colorama si utilisé)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install colorama

      # Étape 4 : Exécuter le script pour vérifier qu'il fonctionne
      - name: Run log analyzer
        run: python log_analyzer.py
